language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - git submodule init
# command to run tests
script:
  - python SportOrg_test.py
  - python setup.py build
branches:
  only:
    - dev